[package]
name = "findjar"
version = "0.1.0"
authors = ["Akshay Ghiya <akshayghiya123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5.1"
grep = "0.2.5"
clap = "2.33.0"
